const locations = [
  {
    countryCode: "HU",
    name: "Magdaléneum Fogyatékosok Református Ápoló Gondozó Otthona",
    place: "Nyíregyháza",
  },
  {
    countryCode: "UA",
    name: "Irgalmas Samaritánus Református Gyermekotthon",
    place: "Velyka Dobron",
  },
  {
    countryCode: "DE",
    name: "Regens Wagner Erlkam",
    place: "Holzkirchen",
  },
  {
    countryCode: "UA",
    name: "Margaréta Óvoda",
    place: "Bodalovo",
  },
  {
    countryCode: "HU",
    name: "Lorántffy Zsuzsanna Református Kismamaház",
    place: "Miskolc",
  },
  {
    countryCode: "HU",
    name: "Kertvárosi Csicsergő Óvoda",
    place: "Nyíregyháza",
  },
  {
    countryCode: "RO",
    name: "Szent István Gyermekotthon",
    place: "Miercurea Ciuc",
  },
  {
    countryCode: "RO",
    name: "Szent Piroska Napköziotthon",
    place: "Bixad",
  },
  {
    countryCode: "RO",
    name: "Gyermek Jézus Otthon",
    place: "Săcueni",
  },
  {
    countryCode: "SK",
    name: "Berzétei Árvaház",
    place: "Brzotín",
  },
  {
    countryCode: "AT",
    name: "Engelbert Kolland Haus",
    place: "Ramsau",
  },
  {
    countryCode: "RO",
    name: "Szent Ferenc Gyermekotthon",
    place: "Băile Tușnad",
  },
  {
    countryCode: "HU",
    name: "Vántus István Általános Iskola",
    place: "Nyírbogát",
  },
  {
    countryCode: "HU",
    name: "Civil Centrum",
    place: "Nyírtelek",
  },
  {
    countryCode: "RO",
    name: "Szent Borbála Napköziotthon",
    place: "Parajd",
  },
  {
    countryCode: "AT",
    name: "S.O.S Kinderdorf",
    place: "Imst",
  },
  {
    countryCode: "AT",
    name: "S.O.S Kinderdorf",
    place: "Wien",
  },
  {
    countryCode: "SK",
    name: "Óvoda",
    place: "Biel",
  },
  {
    countryCode: "RO",
    name: "Aşezare suburbană de romi",
    place: "Săcueni",
  },
  {
    countryCode: "RO",
    name: "Szentháromság otthon",
    place: "Galoșpetreu",
  },
  {
    countryCode: "RO",
    name: "Kéttannyelvű óvoda",
    place: "Satu Mare",
  },
  {
    countryCode: "DE",
    name: "BDP Wilde Rose",
    place: "Geretsried",
  },
  { countryCode: "HU", name: "Várda Hagyomány", place: "Kisvárda" },
  { countryCode: "HU", name: "Kárpát Ház", place: "Kisvárda" },
  { countryCode: "HU", name: "Óvoda", place: "Ecser" },
  { countryCode: "HU", name: "Óvoda", place: "Alsószentmárton" },
  { countryCode: "HU", name: "Óvoda", place: "Salgótarján" },
  {
    countryCode: "HU",
    name: "Fogyatékosok intézete",
    place: "Boldogkőváralja",
  },
  {
    countryCode: "HU",
    name: "Borsod-Abaúj-Zemplén Megyei Önkormányzat Óvoda, Általános Iskola, Előkészítő, Speciális Szakiskola, Kollégium és Egységes Módszertani Intézmény",
    place: "Girincs",
  },
  { countryCode: "HU", name: "Biztos Kezdet Gyerekház", place: "Monok" },
  { countryCode: "HU", name: "Biztos Kezdet Gyerekház", place: "Meggyaszó" },
  { countryCode: "HU", name: "Biztos Kezdet Gyerekház", place: "Prügy" },
  { countryCode: "HU", name: "Óvoda", place: "Karcsa" },
  { countryCode: "HU", name: "Óvoda", place: "Zemplénagárd" },
  { countryCode: "HU", name: "Óvoda", place: "Szabolcsveresmart" },
  { countryCode: "HU", name: "Általános Iskola", place: "Szabolcsveresmart" },
  { countryCode: "HU", name: "Óvoda", place: "Újszentmargita" },
  { countryCode: "HU", name: "Óvoda", place: "Hajdúhadház" },
  { countryCode: "HU", name: "Óvoda", place: "Jászjákóhalma" },
  { countryCode: "HU", name: "Óvoda", place: "Hajdúnánás" },
  { countryCode: "HU", name: "Óvoda", place: "Hajdúböszörmény" },
  { countryCode: "HU", name: "Óvoda", place: "Sárospatak" },
  { countryCode: "HU", name: "Családsegítőközpont", place: "Tokaj" },
  { countryCode: "HU", name: "Önkormányzat", place: "Sárazsadány" },
  { countryCode: "HU", name: "Önkormányzat", place: "Makkoshotyka" },
  { countryCode: "HU", name: "Önkormányzat", place: "Túristvándi" },
  { countryCode: "HU", name: "Önkormányzat", place: "Kömörő" },
  { countryCode: "HU", name: "Családsegítő Központ", place: "Győrtelek" },
  { countryCode: "HU", name: "Önkormányzat", place: "Kocsord" },
  { countryCode: "HU", name: "Óvoda", place: "Kocsord" },
  { countryCode: "HU", name: "Általános Iskola", place: "Záhony" },
  { countryCode: "HU", name: "Központi Óvoda", place: "Kisvárda" },
  { countryCode: "HU", name: "Önkormányzat, ", place: "Szatmárcseke" },
  { countryCode: "HU", name: "Önkormányzat", place: "Jánkmajtis" },
  { countryCode: "HU", name: "Önkormányzat", place: "Nyírjákó" },
  { countryCode: "HU", name: "Önkormányzat", place: "Fehérgyarmat" },
  { countryCode: "HU", name: "Önkormányzat", place: "Tarpa" },
  { countryCode: "HU", name: "Önkrományzat", place: "Beregsurány" },
  { countryCode: "HU", name: "Roma Egyesület", place: "Kótaj" },
  { countryCode: "HU", name: "Roma Egyesület", place: "Ibrány" },
  { countryCode: "HU", name: "Óvoda", place: "Gávavencsellő" },
  { countryCode: "HU", name: "Roma Egyesület", place: "Tiszabercel" },
  { countryCode: "HU", name: "Óvoda", place: "Nyíribrony" },
  { countryCode: "HU", name: "Óvoda", place: "Érpatak" },
  { countryCode: "HU", name: "Önkormányzat", place: "Geszteréd" },
  { countryCode: "HU", name: "Óvoda", place: "Mandabokor" },
  { countryCode: "HU", name: "Magyar Művészeti Egyesület, ", place: "Biri" },
  { countryCode: "HU", name: "Kállói úri Óvoda", place: "Nyíregyháza" },
  { countryCode: "HU", name: "Örökösföldi Óvoda", place: "Nyíregyháza" },
  { countryCode: "HU", name: "Anyaotthon", place: "Nyírszőlős" },
  { countryCode: "HU", name: "Anyaotthon", place: "Nyíregyháza" },
  { countryCode: "HU", name: "Anyaotthon", place: "Sóstóhegy" },
  {
    countryCode: "HU",
    name: "Oltalom Szeretetszolgálat",
    place: "Nyíregyháza-Borbánya",
  },
  {
    countryCode: "HU",
    name: "Göllesz Viktor Speciális Szakiskola",
    place: "Nyíregyháza",
  },
  { countryCode: "HU", name: "Ridens Gimnázium", place: "Nyíregyháza" },
  {
    countryCode: "HU",
    name: "Bárczi Gusztáv Speciális Iskola, Gyógypedagógiai Intézet",
    place: "Debrecen",
  },
  {
    countryCode: "HU",
    name: "Bihari Államigondozottak Egyesülete",
    place: "Debrecen",
  },
  { countryCode: "HU", name: "Fatelepi Óvoda", place: "Debrecen" },
  { countryCode: "HU", name: "Pósa utcai Óvoda", place: "Debrecen" },
  {
    countryCode: "HU",
    name: "Családsegítés",
    place: "Tiszacsermely",
  },
  {
    countryCode: "XK",
    name: "Gyermekotthon",
    place: "Shtime",
  },
  { countryCode: "UA", name: "Óvoda", place: "Velyka Dobron" },
  { countryCode: "UA", name: "Általános Iskola", place: "Velyka Dobron" },
  { countryCode: "UA", name: "Nagydobronyi Líceum", place: "Velyka Dobron" },
  { countryCode: "UA", name: "Óvoda", place: "Mala Dobron" },
  { countryCode: "UA", name: "Égigérő Óvoda", place: "Tysaahtelek" },
  { countryCode: "UA", name: "Önkormányzat", place: "Yasinya" },
  { countryCode: "UA", name: "Manó Óvoda", place: "Yasinya" },
  { countryCode: "UA", name: "Jasla Óvoda", place: "Yasinya" },
  { countryCode: "UA", name: "Óvoda", place: "Bakosh" },
  {
    countryCode: "UA",
    name: "P. Frangepán Katalin Tanóvoda",
    place: "Berehove",
  },
  { countryCode: "UA", name: "Gyerekotthon", place: "Rativtsi" },
  { countryCode: "UA", name: "Óvoda", place: "Tyihlash" },
  { countryCode: "UA", name: "Óvoda", place: "Chop" },
  { countryCode: "UA", name: "Menekültotthon", place: "Mynai" },
  { countryCode: "UA", name: "6-os Iskola", place: "Uzhhorod" },
  { countryCode: "UA", name: "Meseerdő Óvoda", place: "Bene" },
  { countryCode: "UA", name: "Óvoda", place: "Borzhava" },
  { countryCode: "UA", name: "Óvoda", place: "Muzhijevo" },
  { countryCode: "UA", name: "Napocska Óvoda", place: "Choma" },
  { countryCode: "UA", name: "Óvoda", place: "Vary" },
  { countryCode: "UA", name: "Hópehely Óvoda", place: "Hat" },
  { countryCode: "UA", name: "Szivárvány Óvoda és Iskola", place: "Heten" },
  { countryCode: "UA", name: "Általános Iskola", place: "Perekhrestya" },
  {
    countryCode: "UA",
    name: "Református Egyház Közösség",
    place: "Perekhrestya",
  },
  { countryCode: "UA", name: "Kegyes Alapítvány", place: "Perekhrestya" },
  { countryCode: "UA", name: "Óvoda", place: "Vyshkovo" },
  { countryCode: "UA", name: "Óvoda", place: "Dilove" },
  { countryCode: "UA", name: "Gyermekotthon", place: "Svalyavs'kyi" },
  { countryCode: "UA", name: "Kórház", place: "Berehove" },
  { countryCode: "UA", name: "Gyermek Kórház", place: "Uzhhorod" },
  { countryCode: "UA", name: "Kórház", place: "Skole" },
  { countryCode: "UA", name: "Kórház", place: "Dolyna" },
  { countryCode: "UA", name: "Kórház", place: "Sumy" },
  { countryCode: "UA", name: "Kegyes Alapítvány", place: "Perekhrestya" },
  { countryCode: "UA", name: "Központi elosztóraktár", place: "Uzhhorod" },
];

export default locations;
